/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/bobcatfish/testing-crds/client-go/pkg/apis/cat/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCats implements CatInterface
type FakeCats struct {
	Fake *FakeCatV1alpha1
	ns   string
}

var catsResource = schema.GroupVersionResource{Group: "cat.bobcatfish.com", Version: "v1alpha1", Resource: "cats"}

var catsKind = schema.GroupVersionKind{Group: "cat.bobcatfish.com", Version: "v1alpha1", Kind: "Cat"}

// Get takes name of the cat, and returns the corresponding cat object, and an error if there is any.
func (c *FakeCats) Get(name string, options v1.GetOptions) (result *v1alpha1.Cat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(catsResource, c.ns, name), &v1alpha1.Cat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cat), err
}

// List takes label and field selectors, and returns the list of Cats that match those selectors.
func (c *FakeCats) List(opts v1.ListOptions) (result *v1alpha1.CatList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(catsResource, catsKind, c.ns, opts), &v1alpha1.CatList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CatList{ListMeta: obj.(*v1alpha1.CatList).ListMeta}
	for _, item := range obj.(*v1alpha1.CatList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cats.
func (c *FakeCats) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(catsResource, c.ns, opts))

}

// Create takes the representation of a cat and creates it.  Returns the server's representation of the cat, and an error, if there is any.
func (c *FakeCats) Create(cat *v1alpha1.Cat) (result *v1alpha1.Cat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(catsResource, c.ns, cat), &v1alpha1.Cat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cat), err
}

// Update takes the representation of a cat and updates it. Returns the server's representation of the cat, and an error, if there is any.
func (c *FakeCats) Update(cat *v1alpha1.Cat) (result *v1alpha1.Cat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(catsResource, c.ns, cat), &v1alpha1.Cat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cat), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCats) UpdateStatus(cat *v1alpha1.Cat) (*v1alpha1.Cat, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(catsResource, "status", c.ns, cat), &v1alpha1.Cat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cat), err
}

// Delete takes name of the cat and deletes it. Returns an error if one occurs.
func (c *FakeCats) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(catsResource, c.ns, name), &v1alpha1.Cat{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCats) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(catsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CatList{})
	return err
}

// Patch applies the patch and returns the patched cat.
func (c *FakeCats) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Cat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(catsResource, c.ns, name, data, subresources...), &v1alpha1.Cat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cat), err
}
